source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'GeoPackage-iOS-example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GeoPackage-iOS-example
  pod 'geopackage-ios', '~> 7.4.0'
end
